# see colourettu for example on how to seperate unit tests from style tests
sudo: false  # run on new infrastructure
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - nightly
env:
    - PELICAN_VERSION=3.7.1
    - PELICAN_VERSION=false
matrix:
  exclude:
    - env: PELICAN_VERSION=3.7.1
  include:
    - env: PELICAN_VERSION=3.7.1
      python: "3.6"
  allow_failures:
    - python: "2.7"
    - python: nightly
cache: pip
before_install: python -m pip install pip --upgrade
install:
  - pip install .[all]
  - |
    if [ "$PELICAN_VERSION" == "false" ]
    then
      echo "Default Pelican version"
    else
      pip uninstall -y pelican
      pip install pelican==$PELICAN_VERSION
    fi
before_script: pelican --version
script:
  - pycodestyle .
  - python tests/test_image_process.py
