language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
allowed_failures:
  - "nightly"
install: "pip install pelican pillow beautifulsoup4 mock pycodestyle"
script:
  - "pycodestyle ."
  - "python tests/test_image_process.py"
