# see colourettu for example on how to seperate unit tests from style tests
sudo: false  # run on new infrastructure
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
matrix:
  allow_failures:
    - python: "2.7"
    - python: "nightly"
cache: pip
install: "pip install .[all]"
script:
  - "pycodestyle ."
  - "python tests/test_image_process.py"
